### ISSUE TITLE
Maps for the Scenarios

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/AOI_Rework#2]
This is tracker for the maps for the scenarios
Actually didn't decide who would be making the maps.
- [x] Cutscene 1
- [x] Cutscene 2
- [x] Scenario 1
- [x] Scenario 2
- [x] Scenario 3
- [x] Cutscene 3
- [x] Scenario 4 (Final)

**Comment by fable-lake** [comment]
As for the cutscene maps, I can take care of them.
Besides I think cutscene 1 and 2 maps probably would be the same as this is happening in the Lords stronghold.
Yet I must say I m still on 1.14 and campaing is made on 1.15/1.16 so I don't know if the maps made on old one version would be compatibility with the new one version of game.

**Comment by fable-lake** [comment]
I myself would rather avoid creating battle scenario maps because the maps I create could be a bit controversial for some people. And also because the terrain on the maps also strongly influences the gameplay and are created due to the usefulness of the area during the game and the events related to it.
So I can create cutscene scenario maps as a last resort.
We can also try to find someone in the wesnoth community who would be a good map maker for the project if someone would be willingly to do this and if this is possibile solve. 
Besides I think cutscene 1 and 2 maps probably would be the same as this is happening in the same place or can be on two different maps.
